# This is a basic workflow to help you get started with Actions

name: Build Magisk module

# Controls when the workflow will run

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches:
      - 'development'
      - 'stable'
      - 'main'
      - 'master'
    paths-ignore:
      - '.idea/**'
      - '.gitattributes'
      - '.github/**.json'
      - '.gitignore'
      - '**.md'
      - 'LICENSE'
      - 'NOTICE'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - '.idea/**'
      - '.gitattributes'
      - '.github/**.json'
      - '.gitignore'
      - '**.md'
      - 'LICENSE'
      - 'NOTICE'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
env:
  TZ: Europe/Rome 

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3.5.2
        with:
          lfs: true

      - name: Checkout LFS objects
        run: git lfs checkout
        
      - name: Set Timezone
        run: |
          sudo apt-get update
          DEBIAN_FRONTEND=noninteractive sudo apt-get install tzdata
          sudo ln -fs /usr/share/zoneinfo/Europe/Rome /etc/localtime
          sudo dpkg-reconfigure --frontend noninteractive tzdata    
          sudo timedatectl set-timezone Europe/Rome

      - name: Install dependencies
        run: sudo apt-get install --install-recommends zip     

      - name: Build module zip
        run: bash build.sh    

      - name: Upload module zip
        uses: actions/upload-artifact@v3.1.2
        with:
          name: "oneCompleter-actions"
          path: "oneCompleter-v*.zip"
